// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/x1unix/tg-stargazers-bot/internal/config"
	"github.com/x1unix/tg-stargazers-bot/internal/services/bot"
)

// Injectors from wire.go:

// BuildService constructs service instance with app dependencies using Wire.
func BuildService() (*Service, error) {
	commandFlags := config.ReadCommandFlags()
	configConfig, err := config.FromEnv(commandFlags)
	if err != nil {
		return nil, err
	}
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	botConfig := provideBotConfig(configConfig)
	botEventHandler := provideBotEventRouter()
	botService, err := bot.NewService(logger, botConfig, botEventHandler)
	if err != nil {
		return nil, err
	}
	service := NewService(logger, configConfig, botService)
	return service, nil
}
